version: "2"
services:
   docker-moodle-app:
    #  image: php:8.1-fpm
     build:
      context: PHP/
      dockerfile: PHP.Dockerfile
     restart: always
     container_name: docker_moodle-app
     volumes:
       - ./moodle:/var/www/html
       - ./moodledata:/var/www/moodledata
       - ./conf/local.ini:/usr/local/etc/php/php.ini
     networks:
       - docker_moodle
       - docker_jobe
     depends_on:
       - docker_moodle-db
   docker-moodle-web:
     image: nginx
     restart: always
     container_name: docker_moodle-web
     volumes:
       - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
     volumes_from:
       - docker-moodle-app
     ports:
     - "8088:8088"
     networks:
       - docker_moodle
   docker-moodle-db:
     image: mariadb:11.2.2-jammy
     restart: always
     container_name: docker_moodle-db
     environment:
           - MYSQL_USER=moodledude
           - MYSQL_PASSWORD=mysecretpassword
           - MYSQL_DATABASE=moodle
           - MYSQL_ALLOW_EMPTY_PASSWORD=true
     volumes:
           - ./dbdata:/var/lib/mysql
           - ./conf/mycustom.cnf:/etc/mysql/conf.d/custom.cnf
     expose:
           - "3306"
     networks:
           - docker_moodle
   docker-moodle-jobe:
      image: trampgeek/jobeinabox
      container_name: docker_moodle-jobe
      restart: always
      networks:
        - docker_jobe

networks:
  docker_moodle:
      external: false
  docker_jobe:
      external: false

